module Storage.Fill.Regions (fill) where

import Database.SQLite.Simple (Connection, execute)
import qualified Data.Text as T

fill :: Connection -> IO ()
fill db = do
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("dejvice" :: T.Text, 2 :: Int, "Dejvice" :: T.Text, "2A" :: T.Text, "The district demonstrates a commendable commitment to environmental preservation and sustainability. The low levels of pollutants in the air indicate efficient air pollution control measures and a proactive approach towards reducing emissions. This contributes to the overall well-being of the residents and creates a healthier living environment. The good air quality in Dejvice promotes respiratory health, reduces the risk of pollution-related health issues, and enhances the quality of life for its inhabitants. It is a testament to the district's dedication to environmental stewardship and the implementation of eco-friendly practices. Efforts to maintain and improve air quality remain a priority, ensuring a sustainable and ecologically sound future for Dejvice and its residents." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("bubenec" :: T.Text, 2 :: Int, "Bubeneč" :: T.Text, "2B" :: T.Text, "While the air quality is generally acceptable, there are slightly elevated levels of pollutants present in the district. This indicates the need for continued efforts to mitigate pollution sources and improve air quality further. Residents and local authorities should remain vigilant in monitoring and addressing potential environmental concerns to ensure the well-being of the community. Implementing measures to reduce emissions from various sources, such as transportation and industrial activities, can help enhance air quality and create a healthier living environment. Bubeneč has the potential to strengthen its ecological footprint by promoting sustainable practices and encouraging residents to adopt environmentally friendly habits. By raising awareness and implementing effective pollution control strategies, the district can strive towards achieving a higher air quality rating and fostering a more sustainable and ecologically conscious community." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("podbaba" :: T.Text, 1 :: Int, "Podbaba" :: T.Text, "1B" :: T.Text, "While the air quality is generally acceptable, there are slight indications of pollutants present in the district. It is important for the local authorities and residents to remain vigilant in monitoring and addressing potential sources of pollution to maintain and improve the air quality. By implementing measures to reduce emissions from various sources, such as vehicles and industrial activities, the district can further enhance its ecological state. " :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("stromovka" :: T.Text, 1 :: Int, "Stromovka" :: T.Text, "1B" :: T.Text, "As a green oasis within the city, the park offers a refreshing and enjoyable environment for visitors. While there are slight indications of pollutants present, the air quality remains generally acceptable for outdoor activities. Continuous efforts are needed to monitor and address potential sources of pollution within and around the park to maintain its ecological integrity." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("metronom" :: T.Text, 1 :: Int, "Letenské sady" :: T.Text, "1B" :: T.Text, "Nestled in the heart of the city, this green haven offers a tranquil retreat for visitors seeking respite from urban life. While there are slight indications of pollutants present in the air, the overall air quality remains acceptable. It is essential for the park management and visitors to maintain an ecological balance by minimizing potential sources of pollution and promoting sustainable practices. Implementing measures to reduce emissions from nearby areas, such as implementing green transportation options and fostering eco-friendly habits among visitors, will contribute to preserving the park's pristine environment." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("holesovice" :: T.Text, 2 :: Int, "Holešovice" :: T.Text, "2B" :: T.Text, " While the air quality is relatively satisfactory, there are noticeable levels of pollutants present in the district. It is important for both local authorities and residents to address the sources of pollution and take necessary steps to improve the air quality. Implementing measures to reduce emissions from various sources, such as industries and transportation, will be instrumental in enhancing the ecological state of Holešovice. The community's engagement in promoting sustainable practices, supporting green initiatives, and adopting eco-friendly technologies will contribute to a healthier and more environmentally conscious district." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("evrS" :: T.Text, 2 :: Int, "Evropská" :: T.Text, "2A" :: T.Text, "The air quality is generally satisfactory, with low levels of pollutants present. This indicates effective pollution control measures and a proactive approach to reducing emissions." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("hradcany" :: T.Text, 2 :: Int, "Hradčany" :: T.Text, "2B" :: T.Text, "The district experiences moderate levels of pollutants in the air, indicating the need for continued efforts to mitigate pollution sources and improve air quality. While the air quality may not be excellent, it is still within acceptable limits. Residents and local authorities should remain vigilant in monitoring and addressing potential environmental concerns to ensure a healthier living environment. Implementing measures to reduce emissions from various sources, such as transportation and industrial activities, can contribute to enhancing air quality in the district. By raising awareness and encouraging sustainable practices among residents, the district can work towards achieving a higher air quality rating and fostering a more ecologically conscious community." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("vitezne" :: T.Text, 3 :: Int, "Vítězné Náměstí" :: T.Text, "3A" :: T.Text, "While the air quality falls within acceptable limits, there are moderate levels of pollutants present in the district. It is important for both local authorities and residents to take proactive steps in monitoring and addressing potential sources of pollution to improve the air quality further." :: T.Text)
    execute db "INSERT INTO regions (region_name, level, complete_name, status, description) VALUES (?, ?, ?, ?, ?)" ("center" :: T.Text, 3 :: Int, "Staré Město" :: T.Text, "3B" :: T.Text, "The district experiences a noticeable presence of pollutants in the air, indicating the need for ongoing efforts to improve air quality. While the air quality may not be optimal, it remains within acceptable limits. Residents and local authorities should remain proactive in addressing sources of pollution and implementing measures to reduce emissions. By promoting sustainable practices, encouraging eco-friendly transportation options, and raising awareness about the importance of clean air." :: T.Text)
